services:
#    scheduler.example:
#        class: simpleq\SchedulerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.provider:
        class: simpleq\SchedulerBundle\Service\WorkerProvider
        arguments:
            - @simpleq.config.provider
            - @doctrine.dbal.default_connection
    simpleq.scheduler.history.provider:
        class: simpleq\SchedulerBundle\Service\WorkingQueueHistoryProvider
        arguments:
            - @doctrine.dbal.default_connection
    simpleq.scheduler.service:
        class: simpleq\SchedulerBundle\Service\SchedulerService
        arguments:
            - @simpleq.queue.provider
            - @simpleq.worker.provider
            - @simpleq.job.provider
            - @simpleq.worker.run.process