services:
#    worker.example:
#        class: simpleq\WorkerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.run.process:
        class: simpleq\WorkerBundle\Process\WorkerRunProcess
    simpleq.worker.interface:
        class: simpleq\WorkerBundle\Service\WorkerInterface
        abstract: true
    simpleq.base.worker:
        class: simpleq\WorkerBundle\Service\BaseWorker