services:
#    scheduler.example:
#        class: DevGarden\simpleq\SchedulerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.provider:
        class: DevGarden\simpleq\WorkerBundle\Service\WorkerProvider
        arguments:
            - @simpleq.config.provider
            - @doctrine.dbal.default_connection
    simpleq.scheduler.history.provider:
        class: DevGarden\simpleq\SchedulerBundle\Service\WorkingQueueHistoryProvider
        arguments:
            - @doctrine.dbal.default_connection
    simpleq.job.provider:
        class: DevGarden\simpleq\SchedulerBundle\Service\JobProvider
        arguments:
            - @simpleq.queue.provider
            - @simpleq.queue.history.provider
    simpleq.scheduler.service:
        class: DevGarden\simpleq\SchedulerBundle\Service\SchedulerService
        arguments:
            - @simpleq.queue.provider
            - @simpleq.worker.provider
            - @simpleq.job.provider
            - @simpleq.worker.run.process