services:
#    scheduler.example:
#        class: DevGarden\simpleq\SchedulerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.scheduler.history.provider:
        class: DevGarden\simpleq\SchedulerBundle\Service\WorkingQueueHistoryProvider
        arguments:
            - @doctrine
            - @simpleq.worker.provider
    simpleq.scheduler.job.provider:
        class: DevGarden\simpleq\SchedulerBundle\Service\JobProvider
        arguments:
            - @simpleq.queue.provider
    simpleq.scheduler.service:
        class: DevGarden\simpleq\SchedulerBundle\Service\SchedulerService
        arguments:
            - @simpleq.queue.provider
            - @simpleq.worker.provider
            - @simpleq.scheduler.job.provider
            - @simpleq.worker.run.process