services:
#    simpleq.example:
#        class: simpleq\SimpleqBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.config.provider:
        class: simpleq\SimpleqBundle\Service\ConfigProvider
        arguments:
            - '%simpleq.queue%'