language: php
php:
    - 5.5
    #- hhvm
cache:
    directories:
        - $HOME/.composer/cache
before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --no-interaction --prefer-source
script:
    - mkdir -p build/logs
    - phpunit -c app/phpunit.xml.dist --coverage-clover build/logs/clover.xml
after_script:
    #- curl -s https://gist.github.com/satooshi/4750401/raw > travis/ColorCLI.php
    #- curl -s https://gist.github.com/satooshi/4752226/raw > travis/junit.php
    ##- curl -s https://gist.github.com/satooshi/4958593/raw > travis/pmd.php
    #- curl -s https://gist.github.com/satooshi/4958909/raw > travis/checkstyle.php
    #- php travis/checkstyle.php
    #- php travis/pmd.php
    #- php travis/junit.php
    - php vendor/bin/phpunit -c app/phpunit.xml.dist --coverage-clover build/logs/clover.xml
    - php vendor/bin/coveralls -v