<?php

namespace simpleq\WorkerBundle\Extension;

class WorkerStatus
{
    CONST WORKER_STATUS_OPEN_CODE    = 100;
    CONST WORKER_STATUS_OPEN_MESSAGE = 'open';

    CONST WORKER_STATUS_RUNNING_CODE    = 200;
    CONST WORKER_STATUS_RUNNING_MESSAGE = 'running';

    CONST WORKER_STATUS_SUCCESS_CODE    = 300;
    CONST WORKER_STATUS_SUCCESS_MESSAGE = 'success';

    CONST WORKER_STATUS_FAILED_CODE    = 400;
    CONST WORKER_STATUS_FAILED_MESSAGE = 'failed';

    CONST WORKER_STATUS_PENDING_CODE    = 500;
    CONST WORKER_STATUS_PENDING_MESSAGE = 'pending';
}