services:
#    worker.example:
#        class: DevGarden\simpleq\WorkerBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.provider:
        class: DevGarden\simpleq\WorkerBundle\Service\WorkerProvider
        arguments:
            - @simpleq.config.provider
            - @doctrine
    simpleq.worker.run.process:
        class: DevGarden\simpleq\WorkerBundle\Process\WorkerRunProcess
        scope: prototype
    simpleq.base.worker.interface:
        class: DevGarden\simpleq\WorkerBundle\Service\WorkerInterface
        abstract: true
        calls:
            - [setWorkerProvider, [ "@simpleq.worker.provider" ]]
            - [setJobProvider, [ "@simpleq.scheduler.job.provider" ]]
            - [setHistoryProvider, [ "@simpleq.scheduler.history.provider" ]]
    simpleq.base.worker:
        class: DevGarden\simpleq\WorkerBundle\Service\BaseWorker
        parent: simpleq.base.worker.interface