services:
#    demo.example:
#        class: DevGarden\simpleq\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.dummy:
        class: DevGarden\simpleq\DemoBundle\Worker\DummyWorker
        parent: simpleq.base.worker.interface