services:
#    demo.example:
#        class: DevGarden\simpleq\DemoBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    simpleq.worker.dummy.download:
        class: DevGarden\simpleq\DemoBundle\Worker\DummyWorker
    simpleq.worker.dummy.transform:
        class: DevGarden\simpleq\DemoBundle\Worker\DummyWorkerTransform